stages:
  - module-pipelines

backend:
  stage: module-pipelines
  trigger:
    include:
      - "/backend/.gitlab-ci.yml"
    strategy: depend
  only:
    changes:
      - backend/**/*

frontend:
  stage: module-pipelines
  trigger:
    include:
      - "/frontend/.gitlab-ci.yml"
    strategy: depend
  only:
    changes: 
      - frontend/**/*

helm:
  stage: module-pipelines
  trigger:
    include:
      - "/infra/momo-store-chart/.gitlab-ci.yml"
  only:
    changes:
      - /infra/momo-store-chart/**/*
