include:
  - project: 'templates/ci'
    file: 'DockerInDockerTemplate.yml'

variables:
    VERSION: 1.0.${CI_PIPELINE_ID}

stages:
  - test_code
  - build_image

sonarqube-frontend-sast:
  stage: test_code
  image: 
    name: sonarsource/sonar-scanner-cli:latest
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar" 
    GIT_DEPTH: "0" 
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - cd backend
    - >
      sonar-scanner -Dsonar.qualitygate.wait=true \
        -Dsonar.projectKey=15_TSAREVNV_front \
        -Dsonar.sources=. \
        -Dsonar.host.url=https://sonarqube.praktikum-services.ru \
        -Dsonar.login=e7aab173e21292afffa0217566b173d089b5d418
  allow_failure: true
  dependencies:
    -  build_image

build-backend:
  stage: build_image
  image: docker:20.10.12-dind-rootless
  before_script:
    - until docker info; do sleep 1; done
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cd backend
    - >
      docker build
      --build-arg VERSION=$VERSION
      --tag $CI_REGISTRY_IMAGE/momo-backend:$CI_COMMIT_SHA
      .
    - docker push $CI_REGISTRY_IMAGE/momo-backend:$CI_COMMIT_SHA
