stages:
  - push_chart
  - deploy

variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

zip_chart:
  stage: push_chart
  script:
    - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    - chmod 700 get_helm.sh
    - ./get_helm.sh
    # - helm package infra/momo-store-chart
    # - ls
    # - mkdir momo-store-tsarev
    # - helm repo index momo-store-tsarev/ --url https://nexus.k8s.praktikum-services.tech/repository/momo-store-tsarev/
    # - cp momo-store-0.1.0.tgz momo-store-tsarev/
    # - helm repo add nexus http://${NEXUS_REPO_USER}:${NEXUS_REPO_PASS}@nexus.k8s.praktikum-services.tech/repository/momo-store-tsarev/
    # - helm repo list 
    - helm package infra/momo-store-chart
    - curl -u ${NEXUS_REPO_USER}:${NEXUS_REPO_PASS} http://nexus.k8s.praktikum-services.tech/repository/momo-tsarev/ --upload-file momo-store-0.1.0.tgz
    # - helm push momo-store-0.1.0.tgz momo-store-tsarev
    # - curl https://nexus.k8s.praktikum-services.tech/repository/momo-store-tsarev/ -v -F r=momo-store-tsarev -F hasPom=false -F g=momo -F a=momo -F v=${VERSION} -F file=momo-store-0.1.0.tgz -u ${NEXUS_REPO_USER}:${NEXUS_REPO_PASS} 
deploy:
  stage: deploy
  image: alpine/k8s:1.22.15
  environment:
    name: k8s
    url: https://std-015-37.k8s.praktikum-services.tech
  when: manual
  before_script:
    - mkdir -p ~/.kube
    - chmod 700 ~/.kube
    - echo "$KUBECONFIG" >> ~/.kube/config
    - export KUBECONFIG=~/.kube/config
    - chmod 644 ~/.kube/config
  script:
    - kubectl config get-contexts
    - helm repo add nexus http://${NEXUS_REPO_USER}:${NEXUS_REPO_PASS}@nexus.k8s.praktikum-services.tech/repository/momo-tsarev/
    - helm repo update
    - helm repo list
    - helm list
    - helm upgrade momo-store
